nodejs-whatsappBot:
    image: node:14.1
    container_name: nodejs-whatsappBot
    # env_file:
    #   - .env
    restart: always
    volumes:
      - ./bot-app:/src/app
      - /src/app/node_modules
    command: bash -c "cd /src/app && dir &&  npm i && node app.js"
